<?php

function eautopay_menu (){

  $items = array();

  $items['eautopay'] = array(
    'title' => 'POST data',
    'page callback' => 'eautopay_get_post',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/eautopay'] = array(
    'title' => 'Поля профиля из E-autopay',
    'description' => 'Страница созданная модулем e-autopay для дополнительных данных заказа',
    'page callback' => 'rrrrrrrr',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function eautopay_get_post () {

  if($_POST){
    file_put_contents('/tmp/e-autopay.txt', serialize($_POST));
  }


  $result = unserialize(file_get_contents('/tmp/e-autopay.txt'));

  dpm($result);
  dpm(field_info_field('field_tags'));
  return md5($result['id'].$result['email'].$result['phone'].'EEjFUjWNYamxAFLt7Ke7XKtgEw9WphN3sKX7dy');
}

function rrrrrrrr (){
  return'rrrrrrrr';
}