<?php

function eautopay_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'eautopay_views'),
  );
}

function eautopay_views_data() {

  $data['epay_orders']['table']['group'] = t('E-autopay orders');

  $data['epay_orders']['table']['base'] = array(
    'field'    => 'oid',
    'title'    => t('E-Autopay orders'),
  );

  $data['epay_orders']['uid'] = array(
    'title' => t('Relationship with e-autopay user'),
    'help' => t('You can configure orders from e-autopay.com'),
    'relationship' => array(
      'base' => 'users',
      'base field' => 'uid',
      'handler' => 'views_handler_relationship',
      'label' => t('User ID'),
      'title' => t('Relationship with user'),
      'help'  => t('This relationship give you ability to add any field from e-autopay users.'),
    ),
  );

  $data['epay_orders']['oid'] = array(
    'title' => t('Order ID'),
    'help' => t('Order id field.'),
    'field'    => array('handler' => 'views_handler_field_numeric', 'click sortable' => TRUE),
    'filter'   => array('handler' => 'views_handler_filter_numeric'),
    'sort'     => array('handler' => 'views_handler_sort'),
  );

  $data['epay_orders']['order_date'] = array(
    'title' => t('Order date'),
    'help' => t('Order date field.'),
    'field' => array('handler' => 'views_handler_field_date', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort_date'),
    'filter' => array('handler' => 'views_handler_filter_date'),
  );

  $data['epay_orders']['pay_date'] = array(
    'title' => t('Pay date'),
    'help' => t('Pay date field.'),
    'field' => array('handler' => 'views_handler_field_date', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort_date'),
    'filter' => array('handler' => 'views_handler_filter_date'),
  );

  $data['epay_orders']['currency'] = array(
    'title' => t('Currency'),
    'help' => t('Currency field.'),
    'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort'),
    'filter' => array('handler' => 'views_handler_filter_string'),
    'argument' => array('handler' => 'views_handler_argument_string'),
  );

  $data['epay_orders']['product_id'] = array(
    'title' => t('Product ID'),
    'help' => t('Product ID field.'),
    'field'    => array('handler' => 'views_handler_field_numeric', 'click sortable' => TRUE),
    'filter'   => array('handler' => 'views_handler_filter_numeric'),
    'sort'     => array('handler' => 'views_handler_sort'),
  );

  $data['epay_orders']['product_name'] = array(
    'title' => t('Product name'),
    'help' => t('Product name field.'),
    'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort'),
    'filter' => array('handler' => 'views_handler_filter_string'),
    'argument' => array('handler' => 'views_handler_argument_string'),
  );

  $data['epay_orders']['product_price'] = array(
    'title' => t('Product price'),
    'help' => t('Product price field.'),
    'field'    => array('handler' => 'views_handler_field_numeric', 'click sortable' => TRUE),
    'filter'   => array('handler' => 'views_handler_filter_numeric'),
    'sort'     => array('handler' => 'views_handler_sort'),
  );

  $data['epay_orders']['product_qty'] = array(
    'title' => t('Product quantity'),
    'help' => t('Quantity of product.'),
    'field'    => array('handler' => 'views_handler_field_numeric', 'click sortable' => TRUE),
    'filter'   => array('handler' => 'views_handler_filter_numeric'),
    'sort'     => array('handler' => 'views_handler_sort'),
  );

  $data['epay_orders']['comments_client'] = array(
    'title' => t('Client comments'),
    'help' => t('Client comments field.'),
    'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort'),
    'filter' => array('handler' => 'views_handler_filter_string'),
    'argument' => array('handler' => 'views_handler_argument_string'),
  );

  $data['epay_orders']['comments_author'] = array(
    'title' => t('Author comments'),
    'help' => t('Author comments field.'),
    'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort'),
    'filter' => array('handler' => 'views_handler_filter_string'),
    'argument' => array('handler' => 'views_handler_argument_string'),
  );

  $data['epay_orders']['ip'] = array(
    'title' => t('IP'),
    'help' => t('IP address of the client.'),
    'field'    => array('handler' => 'views_handler_field_numeric', 'click sortable' => TRUE),
    'filter'   => array('handler' => 'views_handler_filter_numeric'),
    'sort'     => array('handler' => 'views_handler_sort'),
  );

  $data['epay_orders']['pay_method'] = array(
    'title' => t('Pay method'),
    'help' => t('Pay method field.'),
    'field' => array('handler' => 'views_handler_field', 'click sortable' => TRUE),
    'sort' => array('handler' => 'views_handler_sort'),
    'filter' => array('handler' => 'views_handler_filter_string'),
    'argument' => array('handler' => 'views_handler_argument_string'),
  );

  return $data;
}